agents:
  request_url: https://openrouter.ai/api/v1
  providers:
    acree-ai:
      trinity-large-preview-free:
        model-name: arcee-ai/trinity-large-preview:free
    Nous:
      hermes-3:
        model-name: nousresearch/hermes-3-llama-3.1-405b:free
    inclusionAI:
      Ling-2.6-1T:
        model-name: inclusionai/ling-2.6-1t:free
    tencent:
      hy3-preview:
        model-name: tencent/hy3-preview:free
    MiniMax:
      MiniMax-M2.5:
        model-name: minimax/minimax-m2.5:free
    stepfun:
      step-3.5-flash-free:
        model-name: stepfun/step-3.5-flash:free

  
  